FROM graysonchen/circleci-ruby:2.2.5-jessie

# Verify the circleci user exists before proceeding
RUN whoami

# installations command expect to run as root
USER root

RUN apt update -qq

RUN apt install -y mcrypt libmcrypt-dev libmysqlclient-dev libpq-dev qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x nodejs

USER circleci
